version: '3'

services:

  postgres:
    container_name: postgres_db2
    image: postgres:latest
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mc_schedule